name: datahub-mae-consumer docker
on:
  push:
    branches:
      - master
  release:
    types: [published, edited]

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.repository == 'linkedin/datahub' }}
    steps:
      - uses: actions/checkout@v2
      - uses: ypicard/get-branch-name-github-action@v1
        id: tag
      - uses: docker/build-push-action@v1
        with:
          dockerfile: ./docker/mae-consumer/Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: linkedin/datahub-mae-consumer
          tag_with_ref: true
      - uses: VaultVulp/gp-docker-action@1.1.6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          dockerfile: ./docker/gms/Dockerfile
          image-name: datahub-mae-consumer
          image-tag: ${{ steps.tag.outputs.tag }}
